# default image
image: registry.neuron.id/pub/php:php8-latest

.runner-tag:
  neuron:
    - docker
    - internal

# stage yg dijalankan
stages:
  - code-quality
  - pre-build
  - unit-test
  - build
  - publish
  - deploy
  - automated-security

# ci cache
# cache:
#   key: $CI_COMMIT_REF_SLUG
#   paths:
#     - vendor/

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  SONAR_HOST_URL: "https://sonar.neuronworks.co.id"
  SONAR_SOURCES: "app/Models"

# ---------------------------------------------- Rules Pipeline -----------------------------------------------------
.dev_rules:
  rules:
    - if: '$CI_COMMIT_BRANCH == "development" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'
      variables:
        APP_ENV: development

.staging_rules:
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging-qa" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'
      variables:
        APP_ENV: staging

.prod_rules:
  rules:
    - if: '$CI_COMMIT_TAG =~ "/^doorv3-v.*$/"'
      variables:
        APP_ENV: production

.release_rules:
  rules:
    - if: '$CI_COMMIT_TAG =~ "/^v.*$/"'
      variables:
        APP_ENV: production

# ---------------------------------------------- Pararel Job -----------------------------------------------------
.parallel-matrix-job:
  parallel:
    matrix:
      - APPS:
        - doorv3
        CLIENT_NAME:
          - pgn

# ---------------------------------------------- Code Quality -----------------------------------------------------
sonarqube-check:
  stage: code-quality
  tags: !reference [.runner-tag, neuron]
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=900 -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_TOKEN} -Dsonar.sourceEncoding=UTF-8 -Dsonar.projectName="${CI_PROJECT_NAME} ${CI_COMMIT_REF_NAME}" -Dsonar.projectKey="${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}" -Dsonar.sources=${SONAR_SOURCES}
  rules:
    - !reference [.dev_rules, rules]
    - !reference [.staging_rules, rules]
    - !reference [.prod_rules, rules]
    - !reference [.release_rules, rules]
  allow_failure: true

# ---------------------------------------------- Build Image -----------------------------------------------------
pre-build-apps:
  stage: pre-build
  tags: !reference [.runner-tag, neuron]
  script:
    ## Install BE
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
    ## Install FE
    - apt-get update && apt-get install -y ca-certificates curl gnupg
    - mkdir -vp /etc/apt/keyrings
    - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
    - apt-get update && apt-get install nodejs -y
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    expose_as: "Build FE"
    paths:
      - public/build
      - vendor/
  rules:
    - !reference [.dev_rules, rules]
    - !reference [.staging_rules, rules]
    - !reference [.prod_rules, rules]
    - !reference [.release_rules, rules]

prepare-version:
  stage: pre-build
  tags: !reference [.runner-tag, neuron]
  script:
    - >
      if [ "$APP_ENV" == "production" ]; then
        export APP_VERSION=`date +%Y.%m.%d`-${APP_ENV}_${CI_COMMIT_TAG}
      else
        export APP_VERSION=`date +%Y.%m.%d`-${APP_ENV}_${CI_COMMIT_SHORT_SHA}
      fi
    - echo "APP_ENV=$APP_ENV" > build.env
    - echo "APP_VERSION=$APP_VERSION" >> build.env
  artifacts:
    reports:
      dotenv: build.env
    expire_in: 1 week
  rules:
    - !reference [.dev_rules, rules]
    - !reference [.staging_rules, rules]
    - !reference [.prod_rules, rules]
    - !reference [.release_rules, rules]
    
# ---------------------------------------------- Unit Testing -----------------------------------------------------
phpunit:
  stage: unit-test
  needs:
    ['sonarqube-check', 'pre-build-apps', 'prepare-version']
  tags: !reference [.runner-tag, neuron]
  script:
    - wget -O phpunit https://phar.phpunit.de/phpunit-8.phar -o /dev/null
    - chmod +x phpunit
    - cp ${ENV} .env
    - ./phpunit tests --log-junit report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  allow_failure: true
  environment: $APP_ENV
  rules:
    - !reference [.dev_rules, rules]
    - !reference [.staging_rules, rules]
    - !reference [.prod_rules, rules]

phpunit-client:
  stage: unit-test
  needs:
    ['sonarqube-check', 'pre-build-apps', 'prepare-version']
  parallel: !reference [.parallel-matrix-job, parallel]
  tags: !reference [.runner-tag, neuron]
  script:
    - wget -O phpunit https://phar.phpunit.de/phpunit-8.phar -o /dev/null
    - chmod +x phpunit
    - cp ${ENV} .env
    - ./phpunit tests --log-junit report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  allow_failure: true
  environment: $APP_ENV-$CLIENT_NAME
  rules:
    - !reference [.release_rules, rules]

# ---------------------------------------------- Publish Image -----------------------------------------------------
publish-retail:
  stage: publish
  needs:
    ['sonarqube-check', 'prepare-version', 'pre-build-apps']
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags: !reference [.runner-tag, neuron]
  # script tahapan build docker image
  script:
    # create docker config (json) untuk kaniko --> biar kaniko bisa auth ke container registry gitlab utk push
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --cache=true --cache-repo="${CI_REGISTRY_IMAGE}/cache"
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg=APP_VERSION="$APP_VERSION"
      --destination "${CI_REGISTRY_IMAGE}:${APP_VERSION}"
  #trigger pipeline
  rules:
    - !reference [.dev_rules, rules]
    - !reference [.staging_rules, rules]
    - !reference [.prod_rules, rules]
    - !reference [.release_rules, rules]
  allow_failure: false

# ---------------------------------------------- Deploy App -----------------------------------------------------
trigger-deploy-other-env:
  stage: deploy
  needs: ['sonarqube-check', 'pre-build-apps', 'prepare-version', 'publish-retail']
  variables:
    APP_NAME: retail-services
    APP_ENV: $APP_ENV
    APP_VERSION: $APP_VERSION
  trigger:
    project: devops/doorv3/pgn-retail-service
    strategy: depend
  ##trigger pipeline
  rules:
    - !reference [.prod_rules, rules]
    - !reference [.dev_rules, rules]
    - !reference [.staging_rules, rules]
  allow_failure: false

trigger-deploy-client:
  stage: deploy
  needs: ['sonarqube-check', 'pre-build-apps', 'prepare-version', 'publish-retail']
  variables:
    APP_NAME: retail-services
    APP_ENV: $APP_ENV-$CLIENT_NAME
    CLIENT_NAME: $CLIENT_NAME
    APP_VERSION: $APP_VERSION
  parallel: !reference [.parallel-matrix-job, parallel]
  trigger:
    project: devops/doorv3/pgn-retail-service
    strategy: depend
  ##trigger pipeline
  rules:
    - !reference [.release_rules, rules]
  allow_failure: false
