_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  auto_username: 0
  automated_cron: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  custom_cron: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entitygroupfield: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  group: 0
  hal: 0
  help: 0
  help_description: 0
  history: 0
  image: 0
  jsonapi: 0
  knowledges_telkom: 0
  link: 0
  mail_login: 0
  media_upload: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  passwords: 0
  path: 0
  path_alias: 0
  product_catalog: 0
  publishcontent: 0
  rdf: 0
  rest: 0
  restapi_telkom: 0
  restui: 0
  s3fs: 0
  search: 0
  seckit: 0
  serialization: 0
  shortcut: 0
  single_content_sync: 0
  split_preview: 0
  subgroup: 0
  system: 0
  taxonomy: 0
  templates_telkom: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  variationcache: 0
  view_unpublished: 0
  views_data_export: 0
  views_ui: 0
  workflow: 0
  pathauto: 1
  views: 10
  standard: 1000
theme:
  seven: 0
  stable: 0
  classy: 0
  drupal8_w3css_theme: 0
  telkom_cms: 0
  claro: 0
  gin: 0
profile: standard
