_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  standard__front_page:
    weight: -45
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  entity__user__collection:
    menu_name: main
    parent: 'menu_link_content:abd180d0-21ab-446e-8063-2c1d1a6626a7'
    weight: -50
    expanded: false
    enabled: true
  system__admin_group:
    enabled: false
    menu_name: main
    parent: ''
    expanded: true
    weight: -50
  entity__group__collection:
    weight: -64
    menu_name: main
    parent: system.admin_group
    expanded: false
    enabled: true
  entity__group_type__collection:
    weight: -63
    menu_name: main
    parent: system.admin_group
    expanded: false
    enabled: true
  group__settings:
    weight: -62
    menu_name: main
    parent: system.admin_group
    expanded: false
    enabled: true
