_core:
  default_config_hash: nRysvGldi9bVjwAPJlKXm9C8exWIT4hQhVYJPgYTCWI
favicon:
  mimetype: image/vnd.microsoft.icon
  path: sites/default/files/favicon.ico
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: sites/default/files/favicon.ico
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: auto
classic_toolbar: classic
secondary_toolbar_frontend: true
high_contrast_mode: false
accent_color: ''
focus_color: ''
show_description_toggle: false
show_user_theme_settings: false
