_core:
  default_config_hash: VV0HFGFvi0Pou7lakptNvL-oNLy6iIUp5m6b6gf4xos
credentials_file: ''
bucket: storagetelkomcms
region: ap-southeast-1
use_cname: false
domain_root: none
use_customhost: true
hostname: 'http://10.60.161.'
domain: ''
use_path_style_endpoint: true
disable_version_sync: true
cache_control_header: ''
encryption: ''
use_https: false
ignore_cache: false
read_only: false
disable_cert_verify: true
redirect_styles_ttl: 0
root_folder: ''
public_folder: ''
private_folder: ''
presigned_urls: ''
saveas: ''
torrents: ''
use_cssjs_host: false
cssjs_host: ''
use_credentials_cache: false
credentials_cache_dir: ''
keymodule:
  secret_key_name: ''
  access_key_name: ''
disable_shared_config_files: true
