_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: c073b245-f45a-44b8-b929-eeb12eb7107c
name: 'Telkom CMS Content'
mail: zankanar99@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: noreply-telkomcms@gmail.com
