<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_delete().
 */
function restapi_telkom_entity_delete(EntityInterface $entity) {
  // skip when entity type is not node
  if ($entity->getEntityTypeId() !== 'node') return;

  // retrieve revision status
  $checkRevision = \Drupal::service('media_upload.workflow_helper')->get_approved_id_by_revision_id($entity->id());

  // skip process if this a revision thread
  if (!empty($checkRevision)) return;

  // load library first
  $minioHelper = \Drupal::service('restapi_telkom.minio_helper');

  switch ($entity->bundle()) {
    case 'article':
      // loop through available data
      foreach ($entity->field_image->getValue() as $data) {
        $minioHelper->deleteFile($data['target_id']);
      };
    break;

    case 'news':
      // loop through available data
      foreach ($entity->field_news_image->getValue() as $data) {
        $minioHelper->deleteFile($data['target_id']);
      };
    break;

    case 'landing':
      if (!$entity->field_lan_website_logo->isEmpty()) {
        $imageURL = $entity->field_lan_website_logo->getString();

        // delete file
        $minioHelper->getFileByURI($imageURL, '', 'delete');
      };
    break;

    case 'template':
      // loop through available data
      foreach ($entity->field_tem_image->getValue() as $data) {
        $minioHelper->deleteFile($data['target_id']);
      };
    break;

    case 'template_page':
      // loop through available data
      foreach ($entity->field_tem_page_image->getValue() as $data) {
        $minioHelper->deleteFile($data['target_id']);
      };
    break;

    case 'template_pricing_setting':
      // loop through available data
      foreach ($entity->field_temp_set_logo->getValue() as $data) {
        $minioHelper->deleteFile($data['target_id']);
      };
    break;

    case 'paket_video':
      // loop through available data
      foreach ($entity->field_video_file_video->getValue() as $data) {
        $minioHelper->deleteFile($data['target_id']);
      };
    break;

    case 'paket_media':
      // loop through available data
      foreach ($entity->field_media_image->getValue() as $data) {
        $minioHelper->deleteFile($data['target_id']);
      };
    break;

    case 'paket_content':
      // loop through available data
      foreach ($entity->field_pkt_ctn_media->getValue() as $data) {
        $minioHelper->deleteFile($data['target_id']);
      };
    break;
    
    default:
      break;
  }
}