<?php

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\node\Entity\Node;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Entity\FieldableEntityInterface;

/**
 * Alter query views to search citem/paket/addon
 */
function help_description_views_query_alter($view, $query) {

  // views id => category name
  $mappingMenu = [
    'page_help_approval' => 'approval',
    'page_help_article'  => 'article',
    'page_help_landing_page' => 'landing page',
    'page_help_log' => 'log',
    'page_help_media' => 'media',
    'page_help_product' => 'product',
    'page_help_product_catalog' => 'product catalog',
    'page_help_product_knowledge' => 'product knowledge',
    'page_help_product_specification' => 'product specification',
    'page_help_role' => 'role',
    'page_help_segment' => 'segment',
    'page_help_template' => 'templates',
    'page_help_user' => 'user'
  ];

  if ( in_array($view->id(), array_keys($mappingMenu)) ) {
  
    $term = Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties(['vid' => 'help_category', 'name'=> $mappingMenu[$view->id()]]);
    $term_id = current(array_keys($term));

    // change id to real id in platform (term id in local, dev, or prod server are different)
    foreach ($query->where as $i => &$condition_group) {
      foreach ($condition_group['conditions'] as $j => &$condition) {
        if (str_contains($condition['field'], ':node__field_help_category_field_help_category_target_id')) {
          $condition['value'][':node__field_help_category_field_help_category_target_id'] = $term_id;
        }
      }
    }
    
  }

} 
