<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

function passwords_form_alter(array &$form, FormStateInterface $form_state, $form_id)
{
    if ($form_id === 'user_login_form') {
        $form['#validate'][] = 'testing_validate';
    }
}

function testing_validate(&$form, FormStateInterface &$form_state)
{
    $errors = $form_state->getErrors();
    if (!empty($errors) && array_key_exists('name', $errors)) {
        $form_state->clearErrors();
        $form_state->setErrorByName('name', 'Unrecognized username or password');
    } else if (!empty($form_state->getResponse())) {
        $message = t('Too many failed login attempts from your IP address. This IP address is temporarily blocked. Try again later or <a href=":url">request a new password</a>.', [':url' => Url::fromRoute('passwords.forgot')->toString()]);
        $form_state->getResponse()->setContent($message);
    }
}